app1/urls.py
from django.urls import path

from . import views

app_name='app1'

urlpatterns=[
    path('',views.index, name='index'),
#-------------------상세보기 페이지 추가 210712(태진)--------------------
    path('<int:question_id>/',views.detail, name='detail'),
    path('answer/create/<int:question_id>/',views.answer_create,name='answer_create'),
    #---------------210713 질문등록 url 부여------------------------
    path('question/create/',views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/',views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',views.answer_delete, name='answer_delete'),
    path('testpage3/',views.test,name='test'),



]

common/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'
# session : 일정시간동안 같은 사용자로부터 들어오는 요청을 하나의 상태로 보고 그 상태를 일정하게 유지시키는 기술.
#           사이트 방문자가 사이트에 접속해 있는 상태
# 일정시간 : 사이트에 접속한 시점부터 브라우저 종료까지
# 세션 특징 :
# 1. 웹 서버에 상태를 유지하기 위한 정보를 저장
# 2. 웹 서버에 저장되는 쿠키 - 세션쿠키
urlpatterns =[
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html') , name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('common/',include('common.urls')),
    path('',views.index,name='index')

]

app1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# 질문과 답변 테이블 생성(21.7.8. 김태진 작성)
# 질문테이블 이름 : Question
# 질문 제목 : Subject
# 질문 내용 : Contents
# 질문 작성일자 : Create_date
# 답변테이블 이름 : Answer
#
#---------------질문테이블----------------
class Question(models.Model):
    subject=models.CharField(max_length=100)
    content=models.TextField()
    create_date=models.DateTimeField()

    def __str__(self):
        return self.subject
#--------210721 author컬럼추가------------
#author = 사용자 ID
# on_delete=models.CASCADE -> User에 있는 값이 삭제 되면 해당 값과 연결된 Question테이블의 데이터를 삭제 하나는 의미!
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    #modify_date : 수정일자(작성한 질문에 대한)
    #null=true : 해당 컬럼에 null값 허용
    #blank=true : 폼 데이터 검사시 값이 없어도 된다는 의미
    modify_date = models.DateTimeField(null=True,blank=True)
    def __str__(self):
        return self.subject




#---------------답변테이블----------------
# 답변 내용 : answer_content
# 답변 작성일자 : create_date
# 질문 제목 : question 어떤 질문에 대한 답변인지를 알아햐 하기 때문에

class Answer(models.Model):
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_content=models.TextField()
    create_date=models.DateTimeField()
    # null = true : 컬럼에 null값 허용
    author=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    modify_date = models.DateTimeField(null=True, blank=True)


#--------210721 컬럼추가------------

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{%static 'bootstrap.min.css'%}">
    <script src="{%static 'jquery-3.6.0.min.js'%}"></script>
    <title>베이스</title>
</head>
<body>
<!-- navbar 추가 210716 -->
{% include "navbar.html"  %}

{%block content%}
{%endblock%}
</body>
</html>

templates/form_errors.html
{%if form.errors %}
    {%for field in form%}
        {%for error in field.errors%}
<!--필드오류 출력 / 필드오류 : 입력값 누락, 형식에 맞지않는 값 입력오류-->
            <div class="alert alert-danger" role="alert">
            <strong>{{field.label}}</strong>
            {{error}}
            </div>
        {%endfor%}
    {%endfor%}

        {%for error in form.non_field_errors%}
<!--넌필드 오류 출력 : 넌필드 오류 : 입력값과 관계없이 발생한 오류-->
            <div class="alert alert-danger" role="alert">
            <strong>{{error}}</strong>
            </div>
        {%endfor%}

{%endif%}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'app1:index' %}">프로젝트</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {%if user.is_authenticated%}
                <a class="nav-link" href="{% url 'common:logout' %}">{{user.username}}님(로그아웃)😢</a>
                {% else %}

    <div class="row my-3">
        <div>
            <a href="{%url 'common:login'%}">로그인😊</a>
        </div>
        <div>
            <a href="{%url 'common:signup'%}">회원가입👍</a>
        </div>
        <div>
            <a href="{%url 'app1:test'%}">템플릿 적용시키기🙌</a>
        </div>

                {%endif%}
            </li>
        </ul>
    </div>
</nav>

templates/question_list_백업.html
{%extends 'base.html'%}
{%load filter%}
{%block content%}
<div class="container my-3">
<!--
페이징 : 컴퓨터가 데이터를 저장하고 검색하는 메모리 관리 기법.
paginator.count : 전체 게시물 개수를 가져옴
start_index : 현재 페이지의 시작 인덱스
end_index : 현재 페이지의 끝 인덱스
일렬번호 = 전체 게시물 개수 - 시작 인덱스 - 현재인덱스 + 1
-->
    <table class="table">
    <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>날짜</th>
        </tr>
    </thead>
    <tbody>

    {%if question_list%}
    {%for question in question_list%}
    <tr>
        <td>{{question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}</td>
        <td>
            <a href="{%url 'app1:detail' question.id%}">{{question.subject}}</a>
            {% if question.answer_set.count > 0 %}
            <a href="{%url 'app1:detail' question.id%}"><span class="text-danger small m-2">{{question.answer_set.count}}</span></a>
            {%endif%}
        </td>
        <td>{{question.create_date}}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="3">질문이 없읍니다^^</td>
    </tr>
    {%endif%}
    </tbody>
    </table>
<!--
페이징 처리 view 영역 210719 김태진
-->
    <ul class="pagination justify-content-center">
        {% if question_list.has_previous%}
        <!--has_previous : 이전페이지가 있는지 유무를 확인-->
                <li class="page-item">
            <a class="page-link" href="?page={{question_list.first_page_number}}">맨처음</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{question_list.previous_page_number}}">이전</a>
            <!--has_previous_number : 이전페이지가 번호-->
        </li>

        {%else%}
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-disabled="true" tabindex="-1">fisrt</a>
        </li>
        {%endif%}
        <!-- 페이지 리스트 출력하기-->
        <!-- page_range : 페이지의 범위
             number : 현재 페이지 번호-->

        {%for page_number in question_list.paginator.page_range%}


        {% if page_number >= question_list.number|add:-2 and page_number <= question_list.number|add:2 %}

            {%if page_number == question_list.number%}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
            </li>
            {%else%}
            <li class="page-item">
                <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
            </li>
            {%endif%}
        {%endif%}
        {%endfor%}



        {% if question_list.has_next%}
        <!--has_next : 다음페이지가 있는지 유무를 확인-->

        <li class="page-item">
            <a class="page-link" href="?page={{question_list.next_page_number}}">다음</a>
            <!--has_next_number : 다음페이지 번호-->
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{question_list.paginator.num_pages}}">맨끝</a>
        </li>
        {%else%}
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-disabled="true" tabindex="-1">last</a>
        </li>
        {%endif%}



    </ul>
    <a href="{%url 'app1:question_create'%}" class="btn btn-primary">질문등록하기</a>
</div>
{%endblock%}